language: python
python:
  - 3.6
install: 
  - pip install -r requirements.txt
  - cd frontend
  - npm install
script:
  - npm run lint
  - cd ../
  - flake8 backend/api backend/data
  - isort -c
  - python manage.py test
notifications:
  email: false
