language: python
python:
  - 3.6
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
install: 
  - pip install -r requirements.txt
  - cd frontend
  - npm install
script:
  - npm run lint
  - cd ../
  - flake8 backend/api backend/data
  - isort -c
  - python manage.py test
notifications:
  email: false
